DROP SEQUENCE comments_seq;
DROP TABLE comments CASCADE CONSTRAINTS;

DROP SEQUENCE bulletin_seq;
DROP TABLE bulletin CASCADE CONSTRAINTS;

DROP SEQUENCE hotspot_seq;
DROP TABLE hotspot CASCADE CONSTRAINTS;

DROP SEQUENCE member_seq;
DROP TABLE member CASCADE CONSTRAINTS;


COMMIT;