DROP SEQUENCE reviews_seq;
DROP TABLE reviews CASCADE CONSTRAINTS;

DROP SEQUENCE comments_seq;
DROP TABLE comments CASCADE CONSTRAINTS;

DROP SEQUENCE post_seq;
DROP TABLE posts CASCADE CONSTRAINTS;

DROP SEQUENCE image_seq;
DROP TABLE IMAGEDATA CASCADE CONSTRAINTS;

DROP SEQUENCE user_seq;
DROP TABLE users CASCADE CONSTRAINTS;

COMMIT;